name: Simple Greeting Workflow

on:
  push:
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions! 🎉"
      - name: Say Hello Again
        run: echo "Hello from GitHub Actions AGAIN! 🎉"
